name: build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
          cache: gradle
      - name: Build artifacts
        run: ./gradlew assemble
      - name: Run test suite
        run: ./gradlew check
